create table if not exists chemistry_equations_task_event
(
    event_uuid                  VARCHAR(255) not null primary key,
    event_author_id             VARCHAR(255) not null,
    event_occuring_context      VARCHAR(255) not null,
    event_occuring_context_time TIMESTAMP    not null,
    event_type                  VARCHAR(255) not null,
    event_version               VARCHAR(255),
    event_entity_id             VARCHAR(255),
    event_payload               jsonb        not null
);

CREATE TABLE chemistry_matching_task_event
(
    chemistry_matching_task_event_id                     character varying(255) NOT NULL primary key,
    chemistry_matching_task_event_author_id              character varying(255),
    chemistry_matching_task_event_entity_id              character varying(255),
    chemistry_matching_task_event_occurring_context      character varying(255),
    chemistry_matching_task_event_occurring_context_time timestamp without time zone,
    chemistry_matching_task_event_payload                jsonb,
    chemistry_matching_task_event_type                   character varying(255),
    version                                              character varying(255)
);

create table if not exists chemistry_fixed_answer_task_event
(
    event_uuid                  VARCHAR(255) not null primary key,
    event_author_id             VARCHAR(255) not null,
    event_occuring_context      VARCHAR(255) not null,
    event_occuring_context_time TIMESTAMP    not null,
    event_type                  VARCHAR(255) not null,
    event_version               VARCHAR(255),
    event_entity_id             VARCHAR(255),
    event_payload               jsonb        not null
);

create table chemistry_single_select_task_event
(
    id                    varchar(255) not null
        constraint chemistry_single_select_task_event_pkey
            primary key,
    author_id             varchar(255),
    entity_id             varchar(255),
    event_type            integer,
    event_version         varchar(255),
    occuring_context      varchar(255),
    occuring_context_time timestamp,
    payload               jsonb
);

create table if not exists chem_equation_correct_answers
(
    task_id        varchar(255) not null primary key,
    correct_answer VARCHAR(255)
);

create table if not exists chemfixed_correct_answers
(
    task_id        varchar(255) not null primary key,
    correct_answer VARCHAR(255)
);

create table if not exists cmem_singleselect_correct_answers
(
    task_id        varchar(255) not null primary key,
    correct_answer VARCHAR(255)
);

create table if not exists chem_mathes_correct_answers
(
    task_id varchar(255) not null primary key
);

CREATE TABLE user_answers_correct
(
    id                     bigint generated by default as identity not null primary key,
    user_id                character varying(255),
    user_email             character varying(255),
    correct_answer_task_id character varying(255) unique,
    score                  integer
);

CREATE TABLE correct_couples_for_matching
(
    couple_id    bigint generated by default as identity not null primary key,
    left_couple  character varying(255),
    right_couple character varying(255),
    task_id      character varying(255)
);

alter table if exists correct_couples_for_matching
    add constraint FKk3rytit5j47cc3vfklsommu7i foreign key (task_id) references chem_mathes_correct_answers

