spring:
  application:
    name: answers-task-application
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/answers_task
    username: mick
    password: mick
    platform: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 0
  servlet:
    context-path: /answers-task-application/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  server: http://localhost:9092
  groupId1: fixed-answer-task.2
  groupId2: matching-task.2
  groupId3: tasks-single-select-service.2
  groupId4: equations-task.2

authentication:
  jwt:
    secretKey: chemcool