spring:
  application:
    name: community-application

server:
  port: 0
  servlet:
    context-path: /community-application/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
