spring:
  http:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-discovery:8761/eureka}
  instance:
    metadataMap:
      prometheus:
        path: /actuator/prometheus

ribbon:
  retryableStatusCodes: 503, 504
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  ConnectTimeout: 1500
  ReadTimeout: 7500
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 18000

---
spring:
  profiles: test-hosts

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-discovery:8761/eureka}